### ISSUE TITLE
Possible missing ; on }

### ISSUE THREAD

**Issue by Elvensbane** [samscodeco/SCCLoot#3]
May have spotted a slight typo on this line unless its intended to function this way, but I'm not familar with a function that would use a } in that fashion. 

https://github.com/samscodeco/SCCLoot/blob/0760e54fd2e4c9c50270785447c20765f19dbf75/SCCLoot/System/lootSpawn.sqf#L275

**Comment by samscodeco** [comment]
Fixed in release 0.6.
